---
- name: upload files
  synchronize:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items: '{{ benchmark.put | default([]) }}'

- name: initialize parameters and add number of repetitions
  set_fact:
    parameter_names: ["repetition"]
    parameter_list: '{{ [ num_repetitions ] }}'

- name: unnest parameters when parameters for benchmark were passed
  set_fact:
    parameter_names: '{{ parameter_names + [item.key] }}'
    parameter_list: '{{ parameter_list + [item.value] }}'
  with_dict: '{{ benchmark.parameters | default({}) }}'

- name: parametrized execution
  include_tasks: run-bench-parametrized.yml
  with_cartesian: '{{ parameter_list }}'
  loop_control:
    loop_var: parameter_values
